### ISSUE TITLE
What is the problem with the Chrome Driver? I downloaded it and put it in the assets folder

### ISSUE THREAD

**Issue by alessandrohk** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#25]
I am getting the following message:

Traceback (most recent call last):
  File "/Users/alessandro/Desktop/NFTs_Upload_To_OpenSea_With_Metadata-main/main.py", line 576, in <module>
    opensea = Opensea(password, recovery_phrase)
  File "/Users/alessandro/Desktop/NFTs_Upload_To_OpenSea_With_Metadata-main/main.py", line 153, in __init__
    self.driver = self.webdriver()  # Start new webdriver.
  File "/Users/alessandro/Desktop/NFTs_Upload_To_OpenSea_With_Metadata-main/main.py", line 165, in webdriver
    driver = webdriver.Chrome(self.webdriver_path, options=options)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://chromedriver.chromium.org/home

**Comment by alegar44** [comment]
You are using the windows version of chrome in Mac.... Try this one https://chromedriver.storage.googleapis.com/index.html?path=97.0.4692.71/
Unzip and put it in the same folder (assets). Then modify this code 

`        self.password = password  # Get new password.
        # Used files path.
        self.webdriver_path = 'assets/chromedriver.exe'
        self.metamask_extension_path = 'assets/MetaMask.crx'
        self.driver = self.webdriver()  # Start new webdriver.
`
line 151 with 
`  self.webdriver_path = 'assets/chromedriver.'` (remove the .exe)

Hope this helps

**Comment by Bakhshi007** [comment]
@alegar44 
I have the same issue. and I followed things you have mentioned but still get the same error.
