### ISSUE TITLE
Getting this error pls help

### ISSUE THREAD

**Issue by Unknowns121** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#30]
D:\generate-nfts-main\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py:165: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(self.webdriver_path, options=options)

DevTools listening on ws://127.0.0.1:64863/devtools/browser/9da6b137-40bd-4af7-bde3-f44797c349ff
Traceback (most recent call last):
  File "D:\generate-nfts-main\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 576, in <module>
    opensea = Opensea(password, recovery_phrase)
  File "D:\generate-nfts-main\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 153, in __init__
    self.driver = self.webdriver()  # Start new webdriver.
  File "D:\generate-nfts-main\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 165, in webdriver
    driver = webdriver.Chrome(self.webdriver_path, options=options)
  File "C:\Users\dhyey\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\dhyey\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\dhyey\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\dhyey\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 357, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\dhyey\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\dhyey\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 96
Current browser version is 98.0.4758.81 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by Unknowns121** [comment]
downloaded cromedriver 98 then also

**Comment by Mohammadkhare** [comment]
my problem too

**Comment by nftdevs** [comment]
Can you please download [ChromeDriver](https://chromedriver.storage.googleapis.com/index.html?path=98.0.4758.80/) and try again.
