### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by Mohammadkhare** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#44]
its too slow and sometimes wont work

**Comment by nftdevs** [comment]
Can you give us more information please.

**Comment by lotz384** [comment]
Hi @nftdevs , I'm having the same problem. 

I'm trying to upload a collection of 15,000 png's since 28/02/2022. At this time, 9am at 04/03/2022, I only uploaded 3762 png's. 

The problem is that after every 70-250 uploads the code stops and this error appears: 

`Uploading NFT 71/11309. NFT uploaded.
Data saved in data/9343ec99.csv
Sale of the NFT 71/11309. NFT put up for sale.
Login to MetaMask. Login to MetaMask failed. Restarting.
Login to OpenSea. Login to OpenSea failed. Retrying.
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Python310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023E7C274430>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\NFT\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 333, in login
    web.window_handles(1)  # Switch to the main (data:,) tab.
  File "D:\NFT\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 248, in window_handles
    WDW(self.driver, 30).until(lambda _: len(
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "D:\NFT\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 249, in <lambda>
    self.driver.window_handles) > window_number)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 977, in window_handles
    return self.execute(Command.W3C_GET_WINDOW_HANDLES)['value']
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 423, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 316, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 338, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Python310\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Python310\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Python310\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=61411): Max retries exceeded with url: /session/b6ec54e56482088ef0480dd24948adfc/window/handles (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E7C274430>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Python310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023E7C253BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\NFT\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 351, in login
    web.window_handles(1)  # Switch back to the OpenSea tab.
  File "D:\NFT\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 248, in window_handles
    WDW(self.driver, 30).until(lambda _: len(
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "D:\NFT\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 249, in <lambda>
    self.driver.window_handles) > window_number)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 977, in window_handles
    return self.execute(Command.W3C_GET_WINDOW_HANDLES)['value']
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 423, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 316, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 338, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Python310\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Python310\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Python310\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=61411): Max retries exceeded with url: /session/b6ec54e56482088ef0480dd24948adfc/window/handles (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E7C253BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Python310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Python310\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023E7C252B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\NFT\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 653, in <module>
    opensea.login()  # Connect to OpenSea.
  File "D:\NFT\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 362, in login
    web.driver.refresh()
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1062, in refresh
    self.execute(Command.REFRESH)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 423, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 316, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 338, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Python310\lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
  File "C:\Python310\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Python310\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "C:\Python310\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Python310\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=61411): Max retries exceeded with url: /session/b6ec54e56482088ef0480dd24948adfc/refresh (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E7C252B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`

I did everything as in the [video](https://www.youtube.com/watch?v=OfqmR2lvU8E). I also made sure my PC doesn't enter sleep mode as to not interrupt the upload.

I hope you can help me.

PS: I think it would also accelerate the upload if you didn't closed the window and logged in again at metamask and OpenSea, as I often get (this) errors because he couldn't logged in.
