### ISSUE TITLE
Driver is correct, but error

### ISSUE THREAD

**Issue by Jorddd** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#60]
This is the error:

Traceback (most recent call last):
  File "C:\NFT\script automatico\3\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 650, in <module>
    web = Webdriver()  # Start a new webdriver and init its methods.
  File "C:\NFT\script automatico\3\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 189, in __init__
    self.driver = self.webdriver()  # Start new webdriver.
  File "C:\NFT\script automatico\3\NFTs_Upload_To_OpenSea_With_Metadata-main\main.py", line 201, in webdriver
    driver = webdriver.Chrome(service=Service(  # DeprecationWarning using
  File "C:\Users\Jordan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Jordan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Jordan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Jordan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Jordan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Jordan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 99
Current browser version is 98.0.4758.102 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x00669943+2595139]
        Ordinal0 [0x005FC9F1+2148849]
        Ordinal0 [0x004F4528+1066280]
        Ordinal0 [0x005142C3+1196739]
        Ordinal0 [0x0050FE37+1179191]
        Ordinal0 [0x0050D6F1+1169137]
        Ordinal0 [0x00540530+1377584]
        Ordinal0 [0x0054018A+1376650]
        Ordinal0 [0x0053B806+1357830]
        Ordinal0 [0x00516086+1204358]
        Ordinal0 [0x00516F96+1208214]
        GetHandleVerifier [0x0080B232+1658114]
        GetHandleVerifier [0x008C312C+2411516]
        GetHandleVerifier [0x006FF261+560433]
        GetHandleVerifier [0x006FE366+556598]
        Ordinal0 [0x0060286B+2173035]
        Ordinal0 [0x006075F8+2192888]
        Ordinal0 [0x006076E5+2193125]
        Ordinal0 [0x006111FC+2232828]
        BaseThreadInitThunk [0x7712FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77E37A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77E37A6E+238]

It already uploaded over 600 nft, then it stops. I changed only the json file (as the tutorial said). 
I downloaded again the chrome driver version 98 as my chrome version.
Why it's not working and before was working fine?

**Comment by fern00-n** [comment]
same is happening to me, but idk how to fix it srry.

**Comment by manojwickramasinghe** [comment]
I'm also having the same issue
tried downloading chrome again and again

Traceback (most recent call last):
  File "E:\mask nft\newly down code\NFTs_Upload_To_OpenSea_With_Metadata-main\ma
in.py", line 650, in <module>
    web = Webdriver()  # Start a new webdriver and init its methods.
  File "E:\mask nft\newly down code\NFTs_Upload_To_OpenSea_With_Metadata-main\ma
in.py", line 189, in __init__
    self.driver = self.webdriver()  # Start new webdriver.
  File "E:\mask nft\newly down code\NFTs_Upload_To_OpenSea_With_Metadata-main\ma
in.py", line 202, in webdriver
    CDM(log_level=0).install()), options=options)  # executable_path.
  File "C:\Users\Manoj\AppData\Local\Programs\Python\Python310\lib\site-packages
\webdriver_manager\chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Users\Manoj\AppData\Local\Programs\Python\Python310\lib\site-packages
\webdriver_manager\manager.py", line 25, in _get_driver_path
    binary_path = self.driver_cache.find_driver(browser_version, driver_name, os
_type,
  File "C:\Users\Manoj\AppData\Local\Programs\Python\Python310\lib\site-packages
\webdriver_manager\driver_cache.py", line 66, in find_driver
    metadata = self.get_metadata()
  File "C:\Users\Manoj\AppData\Local\Programs\Python\Python310\lib\site-packages
\webdriver_manager\driver_cache.py", line 96, in get_metadata
    return json.load(outfile)
  File "C:\Users\Manoj\AppData\Local\Programs\Python\Python310\lib\json\__init__
.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Manoj\AppData\Local\Programs\Python\Python310\lib\json\__init__
.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Manoj\AppData\Local\Programs\Python\Python310\lib\json\decoder.
py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Manoj\AppData\Local\Programs\Python\Python310\lib\json\decoder.
py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

E:\mask nft\newly down code\NFTs_Upload_To_OpenSea_With_Metadata-main>
