### ISSUE TITLE
I can't launch main.py

### ISSUE THREAD

**Issue by kbusqueta** [nftdevs/NFTs_Upload_To_OpenSea_With_Metadata#68]
Hi ! 😄  I've got a problem when I launch the Python3 main.py command. 
I can choose my json file but I after that I've got this problem : 
Traceback (most recent call last):
  File "/Users/kevinbusqueta/Downloads/NFTs_Upload_To_OpenSea_With_Metadata-main/main.py", line 646, in <module>
    reader = Reader(data_file())  # Ask for a file and read it.
  File "/Users/kevinbusqueta/Downloads/NFTs_Upload_To_OpenSea_With_Metadata-main/main.py", line 43, in __init__
    eval(f'self.extract_{self.extension}_file()')
  File "<string>", line 1, in <module>
  File "/Users/kevinbusqueta/Downloads/NFTs_Upload_To_OpenSea_With_Metadata-main/main.py", line 52, in extract_json_file
    self.file = loads(open(self.path, encoding='utf-8').read())['nft']
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 1 (char 652) 

After that nothing happens. 
Can you help me ? 
Thank you 😄

**Comment by kbusqueta** [comment]
If I upload just one NFT it works but not when I've got 2 or more in my metadata file
